# travis
# -*- coding: utf-8 -*-

## Dependencies:    python-mechanize, python-keyring, curses
## Author:          Gijs Timmers: https://github.com/GijsTimmers
## Contributors:    Gijs Timmers: https://github.com/GijsTimmers
##                  Jo Van Bulck: https://github.com/jovanbulck

## Licence:         CC-BY-SA-4.0
##                  https://creativecommons.org/licenses/by-sa/4.0/

## This work is licensed under the Creative Commons
## Attribution-ShareAlike 4.0 International License. To view a copy of 
## this license, visit https://creativecommons.org/licenses/by-sa/4.0/ or
## send a letter to Creative Commons, PO Box 1866, Mountain View, 
## CA 94042, USA.

## Moving to container-based infrastructure
sudo: false

## Setting up the correct language
language: python
python: "2.7"

## Command to install system dependencies
addons:
  apt:
    packages:
    - dialog
    - python-dbus
    - python-dbus-dev

## Command to install system dependencies
before_install: 
    - git clone https://github.com/pyinstaller/pyinstaller.git
#    - cp -r /usr/lib/python2.7/dist-packages/dbus /home/travis/virtualenv/python2.7.8/site-packages/        
#    - cp -r /usr/lib/python2.7/dist-packages/_dbus_*.so /home/travis/virtualenv/python2.7.8/site-packages/
#    - sudo apt-get install libdbus-glib-1-dev
#    - wget http://dbus.freedesktop.org/releases/dbus-python/dbus-python-1.2.0.tar.gz
#    - mkdir dbus
#    - tar xvzf dbus-python-1.2.0.tar.gz -C dbus --strip-components=1
#    - cd dbus
#    - ./configure --prefix=/tmp/dbus-python
#    - make
#    - sudo make install
    
## Command to install pip dependencies
install: 
    - pip install keyring colorama python2-pythondialog \
      beautifulsoup4 argcomplete
#    - pip install dbus-python

## command to run tests
script: nosetests
    
    #- ./kotnetcli.py -h
    #- ./kotnetcli.py -1 -c 
    #- ./kotnetcli.py -1 -u
    #- ./kotnetcli.py -1 -t
    #- ./kotnetcli.py -1 -d
    #- ./kotnetcli.py -1 -s
    #- ./kotnetcli.py -1 -q
    #- ./kotnetcli.py -0 -c
    #- ./kotnetcli.py -0 -u
    #- ./kotnetcli.py -0 -t
    #- ./kotnetcli.py -0 -d
    #- ./kotnetcli.py -0 -s
    #- ./kotnetcli.py -0 -q
    #- ./pyinstaller/pyinstaller.py compile-lin.spec
    #- ./dist/kotnetcli-lin -h
    #- ./dist/kotnetcli-lin -1 -c 
    #- ./dist/kotnetcli-lin -1 -u
    #- ./dist/kotnetcli-lin -1 -t
    #- ./dist/kotnetcli-lin -1 -d
    #- ./dist/kotnetcli-lin -1 -s
    #- ./dist/kotnetcli-lin -1 -q
    #- ./dist/kotnetcli-lin -0 -c
    #- ./dist/kotnetcli-lin -0 -u
    #- ./dist/kotnetcli-lin -0 -t
    #- ./dist/kotnetcli-lin -0 -d
    #- ./dist/kotnetcli-lin -0 -s
    #- ./dist/kotnetcli-lin -0 -q
    #- ./kotnetcli_test.py --run-tests

notifications:
    - email: false
