dummy_user:
  download: 75
  pwd: dummy_password
  upload: 90
foo:
  download: 20
  pwd: bar
  upload: 60
gijs:
  download: 0
  pwd: wies
  upload: 0
jo:
  download: 100
  pwd: very_secret
  upload: 100
